const en = {
  header_brand: 'whatif.lat',
  header_subtitle: 'What if…? 🤔⚽',
  nav_home: 'Home',
  nav_explorar: 'Explore',
  nav_aria: 'Main',
  nav_open_menu: 'Open menu',
  nav_close_menu: 'Close menu',
  btn_login: 'Log in',
  btn_logout: 'Log out',

  home_meta_title: 'whatif.lat — What if…? Alternate football history',
  home_meta_desc: 'Pick an iconic football moment, change one variable, and AI tells you the alternate story. Free, no signup.',
  home_title: 'What if…? 🤔⚽',
  home_subtitle: 'Pick an iconic football moment. Change one variable. Discover the alternate story in seconds.',

  momento_choose_variable: 'Pick an alternate scenario',
  momento_or_custom: 'Or write your own',
  momento_custom_placeholder: 'e.g. What if the ref disallows the goal?',
  momento_generate_btn: '✨ Generate story',
  momento_err_select: 'Pick an option or write your own scenario (min 5 chars).',
  momento_not_found: 'Moment not found.',

  historia_not_found: 'Story not found.',
  historia_more_variants: 'Other scenarios',
  historia_new: 'New story',

  tarjeta_copiar: '📋 Copy',
  tarjeta_copiado: '✅ Copied!',
  tarjeta_compartir: '🔗 Share',

  explorar_title: 'Explore stories',
  explorar_lead: 'Latest alternate stories generated by other football fans.',
  explorar_empty: 'No stories yet. Be the first!',

  gen_err_fallback: 'Could not generate the story. Try again.',

  auth_title: 'Your account',
  auth_subtitle: 'Optional. Only for saving your stories.',
  auth_tab_login: 'Log in',
  auth_tab_register: 'Register',
  auth_label_email: 'Email',
  auth_placeholder_email: 'you@email.com',
  auth_label_password: 'Password',
  auth_placeholder_password: '••••••••',
  auth_btn_processing: 'Processing…',
  auth_btn_login: 'Log in',
  auth_btn_register: 'Create account',
  auth_msg_confirm: 'Check your email to confirm the account.',
  auth_err_fallback: 'Could not complete the action.',
  auth_skip: '← Back without account',

  verified_title: 'Email verified!',
  verified_body: 'Your account is ready.',
  verified_btn: 'Go home',
  verified_error_title: 'Something went wrong',
  verified_error_body: 'The link may have expired.',

  loading: 'Loading…',
}

export default en
