const clamp01=value=>Math.max(0,Math.min(1,value))
const smoothstep=value=>{const t=clamp01(value);return t*t*(3-2*t)}
const lerp=(a,b,t)=>a+(b-a)*t
const frac=value=>value-Math.floor(value)

export function renderAutomationSubworld({ctx,camera,time,viewport,nodes,focus,intensity,palette}) {
  if(intensity<=.01||nodes.length<3)return
  const {width,height}=viewport,{gold,pearl,smoke,rgba}=palette,cameraScale=Math.max(1,Math.min(1.78,camera.zoom/.86)),innerRadius=Math.min(width,height)*.17*cameraScale,outerRadius=innerRadius*(.25/.17),crestCount=7,samples=12,averageDepth=nodes.reduce((sum,node)=>sum+clamp01((node.z+1)/2),0)/nodes.length,crests=[]
  for(let crest=0;crest<crestCount;crest++){const points=[],row=(crest-(crestCount-1)/2)*innerRadius*.19,amplitude=innerRadius*(.075+(crest%3)*.012),frequency=1.42+(crest%2)*.18,phase=crest*.57+Math.sin(crest*1.7)*.24;for(let sample=0;sample<samples;sample++){const progress=sample/(samples-1),u=lerp(-innerRadius*.96,innerRadius*.96,progress),flowPhase=progress*Math.PI*2*frequency+phase-time*(.2+crest*.006),wave=Math.sin(flowPhase)*amplitude+Math.cos(flowPhase*.53+crest)*amplitude*.18,distance=Math.hypot(u,row+wave),fade=1-smoothstep((distance-innerRadius)/(outerRadius-innerRadius)),depth=clamp01(.2+averageDepth*.28+(1-Math.abs(crest-(crestCount-1)/2)/(crestCount*.62))*.38+wave/innerRadius*.08),perspective=.94+depth*.075;points.push({x:focus.x+u*perspective,y:focus.y+(row+wave)*perspective,z:depth,fade,crest,sample})}crests.push(points)}
  ctx.save();const field=ctx.createRadialGradient(focus.x,focus.y,innerRadius*.16,focus.x,focus.y,outerRadius);field.addColorStop(0,rgba('#171a20',.115*intensity));field.addColorStop(.7,rgba('#0b0d11',.04*intensity));field.addColorStop(1,'transparent');ctx.fillStyle=field;ctx.beginPath();ctx.arc(focus.x,focus.y,outerRadius,0,Math.PI*2);ctx.fill()
  crests.forEach((points,crest)=>{const depth=points.reduce((sum,point)=>sum+point.z,0)/points.length,fade=points.reduce((sum,point)=>sum+point.fade,0)/points.length;ctx.strokeStyle=rgba(crest===3?pearl:smoke,(crest===3?.34:.22)*depth*fade*intensity);ctx.lineWidth=crest===3?.76:.5;ctx.beginPath();ctx.moveTo(points[0].x,points[0].y);for(let index=1;index<points.length-1;index++){const midpointX=(points[index].x+points[index+1].x)/2,midpointY=(points[index].y+points[index+1].y)/2;ctx.quadraticCurveTo(points[index].x,points[index].y,midpointX,midpointY)}ctx.lineTo(points.at(-1).x,points.at(-1).y);ctx.stroke()})
  const crossings=[[1,3,4],[2,4,7],[3,5,5]];crossings.forEach(([from,to,sample],index)=>{const a=crests[from][sample],b=crests[to][Math.min(samples-1,sample+1)],fade=Math.min(a.fade,b.fade),midX=(a.x+b.x)/2+innerRadius*(index-1)*.025,midY=(a.y+b.y)/2;ctx.strokeStyle=rgba(index===1?gold:pearl,.24*fade*intensity);ctx.lineWidth=.58;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.quadraticCurveTo(midX,midY,b.x,b.y);ctx.stroke();ctx.fillStyle=rgba(index===1?gold:pearl,.72*fade*intensity);ctx.beginPath();ctx.arc(midX,midY,index===1?2.05:1.45,0,Math.PI*2);ctx.fill()})
  for(let pulse=0;pulse<15;pulse++){const crest=(pulse*5)%crestCount,points=crests[crest],phase=frac(time*(.052+(pulse%4)*.006)+pulse*.127),position=phase*(samples-1),index=Math.min(samples-2,Math.floor(position)),local=position-index,a=points[index],b=points[index+1],envelope=Math.sin(phase*Math.PI)**.72,fade=lerp(a.fade,b.fade,local),depth=lerp(a.z,b.z,local);ctx.fillStyle=rgba(pulse%5===0?gold:pearl,envelope*(.28+depth*.68)*fade*intensity);ctx.beginPath();ctx.arc(lerp(a.x,b.x,local),lerp(a.y,b.y,local),.78+depth*.7,0,Math.PI*2);ctx.fill()}
  crests.flat().forEach(point=>{const key=point.sample===4||point.sample===7,active=key&&point.crest%2===1;ctx.fillStyle=rgba(active?gold:pearl,(active?.5:.24)*point.z*point.fade*intensity);ctx.beginPath();ctx.arc(point.x,point.y,active?1.32:.68,0,Math.PI*2);ctx.fill()});ctx.restore()
}
