const clamp01=value=>Math.max(0,Math.min(1,value))
const smoothstep=value=>{const t=clamp01(value);return t*t*(3-2*t)}
const lerp=(a,b,t)=>a+(b-a)*t
const frac=value=>value-Math.floor(value)
const hash2=(x,y)=>frac(Math.sin(x*127.1+y*311.7)*43758.5453)
const valueNoise=(x,y)=>{const ix=Math.floor(x),iy=Math.floor(y),fx=x-ix,fy=y-iy,sx=fx*fx*(3-2*fx),sy=fy*fy*(3-2*fy),a=lerp(hash2(ix,iy),hash2(ix+1,iy),sx),b=lerp(hash2(ix,iy+1),hash2(ix+1,iy+1),sx);return lerp(a,b,sy)}
const terrainNoise=(x,y)=>valueNoise(x*.72+3.7,y*.72+8.1)*.68+valueNoise(x*1.34+17.2,y*1.34+4.6)*.32
const hill=(x,z,cx,cz,width,depth)=>Math.exp(-(Math.pow((x-cx)/width,2)+Math.pow((z-cz)/depth,2)))
const projectTerrainVertex=({worldX,worldY,worldZ,focus,horizonY,foregroundDepth})=>{const perspective=.91+worldZ*.09;return{x:focus.x+worldX*perspective,y:horizonY+worldZ*foregroundDepth-worldY*(.54+worldZ*.34)}}

export function renderIaSubworld({ctx,camera,time,viewport,nodes,focus,intensity,palette}) {
  if(intensity<=.01||nodes.length<3)return
  const {width,height}=viewport,{gold,pearl,rgba}=palette,cameraScale=Math.max(1,Math.min(1.82,camera.zoom/.86)),innerRadius=Math.min(width,height)*.17*cameraScale,outerRadius=innerRadius*(.25/.17)
  const columns=17,rows=10,averageDepth=nodes.reduce((sum,node)=>sum+clamp01((node.z+1)/2),0)/nodes.length,horizonY=focus.y-innerRadius*.42,foregroundDepth=Math.max(innerRadius*1.56,height-horizonY-8),edgeDistance=Math.max(focus.x,width-focus.x),horizonHalfWidth=edgeDistance/0.91*1.04,foregroundHalfWidth=edgeDistance/.99*1.14,vertices=[]
  for(let row=0;row<rows;row++)for(let column=0;column<columns;column++){
    const depthProgress=clamp01((row+(column%2?.5:0))/(rows-.5)),groundDepth=depthProgress**1.28,lateral=(column-(columns-1)/2)/(columns-1),halfWidth=lerp(horizonHalfWidth,foregroundHalfWidth,groundDepth**.72),waveA=Math.sin(time*.78-groundDepth*7.4+lateral*1.1),waveB=Math.sin(time*.55-groundDepth*4.2-lateral*2.3+1.4),horizontalA=Math.sin(time*.61-groundDepth*5.1+lateral*4.3+.7),horizontalB=Math.sin(time*.45+groundDepth*3.6+lateral*6.2+2.1),edgeFade=.78+.22*(1-smoothstep((Math.abs(lateral)-.44)/.07)),noiseHeight=(terrainNoise(lateral*1.9,groundDepth*1.75)-.5)*innerRadius*.42,peaks=(hill(lateral,groundDepth,-.31,.34,.2,.18)*.5+hill(lateral,groundDepth,.12,.48,.18,.2)*.42+hill(lateral,groundDepth,.38,.27,.14,.15)*.34)*innerRadius,terrainElevation=noiseHeight+peaks,displacement=(waveA*.7+waveB*.36)*innerRadius*.052*edgeFade,horizontalDisplacement=(horizontalA*.64+horizontalB*.31)*innerRadius*.029*edgeFade*(.62+groundDepth*.38),worldX=lateral*2*halfWidth+horizontalDisplacement,worldY=terrainElevation+displacement,projected=projectTerrainVertex({worldX,worldY,worldZ:groundDepth,focus,horizonY,foregroundDepth}),depth=clamp01(.18+averageDepth*.18+groundDepth*.62+worldY/innerRadius*.035),localFade=edgeFade*(.42+groundDepth*.58)
    vertices.push({row,column,x:projected.x,y:projected.y,z:depth,fade:localFade,worldX,worldY,worldZ:groundDepth,terrainElevation,displacement,horizontalDisplacement})
  }
  const at=(row,column)=>vertices[row*columns+column],edges=[],addEdge=(a,b)=>{const valley=Math.max(a.terrainElevation,b.terrainElevation)<innerRadius*.045,keep=!valley||hash2(a.row*3+a.column,b.row*5+b.column)<.58;if(keep)edges.push([a,b])}
  vertices.forEach(vertex=>{if(vertex.row<rows-1)addEdge(vertex,at(vertex.row+1,vertex.column));if(vertex.column<columns-1){addEdge(vertex,at(vertex.row,vertex.column+1));const diagonalRow=vertex.row+(vertex.column%2?1:-1);if(diagonalRow>=0&&diagonalRow<rows)addEdge(vertex,at(diagonalRow,vertex.column+1))}})
  ctx.save()
  const field=ctx.createRadialGradient(focus.x,focus.y,innerRadius*.18,focus.x,focus.y,outerRadius);field.addColorStop(0,rgba('#171a20',.12*intensity));field.addColorStop(.68,rgba('#0b0d11',.045*intensity));field.addColorStop(1,'transparent');ctx.fillStyle=field;ctx.beginPath();ctx.arc(focus.x,focus.y,outerRadius,0,Math.PI*2);ctx.fill()
  edges.sort((a,b)=>(a[0].z+a[1].z)-(b[0].z+b[1].z)).forEach(([a,b])=>{const fade=Math.min(a.fade,b.fade),depth=.2+((a.z+b.z)*.5)*.8,strain=Math.hypot(a.displacement-b.displacement,a.horizontalDisplacement-b.horizontalDisplacement)/Math.max(1,innerRadius*.052),active=strain>.48,localIntensity=.78+hash2(a.row*11+a.column,b.row*7+b.column)*.38;ctx.strokeStyle=rgba(pearl,(active?.64:.48)*localIntensity*depth*fade*intensity);ctx.lineWidth=active?1.08:.82;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()})
  for(let pulse=0;pulse<12;pulse++){const edge=edges[(pulse*17)%edges.length],phase=frac(time*(.064+(pulse%4)*.008)+pulse*.137),envelope=Math.sin(phase*Math.PI)**1.35,fade=Math.min(edge[0].fade,edge[1].fade),x=lerp(edge[0].x,edge[1].x,phase),y=lerp(edge[0].y,edge[1].y,phase),depth=(edge[0].z+edge[1].z)*.5;ctx.fillStyle=rgba(pulse%4===0?gold:pearl,envelope*(.24+depth*.7)*fade*intensity);ctx.beginPath();ctx.arc(x,y,.7+depth*.62,0,Math.PI*2);ctx.fill()}
  vertices.sort((a,b)=>a.z-b.z).forEach(vertex=>{const degree=(vertex.column>0?1:0)+(vertex.column<columns-1?1:0)+(vertex.row>0?2:0)+(vertex.row<rows-1?2:0),intersection=degree>=6,accent=intersection&&(vertex.row*5+vertex.column*3)%13===0,depth=.2+vertex.z*.8,localIntensity=.8+hash2(vertex.row*17,vertex.column*23)*.34;ctx.fillStyle=rgba(accent?gold:pearl,(accent?.84:intersection?.78:.64)*localIntensity*depth*vertex.fade*intensity);ctx.beginPath();ctx.arc(vertex.x,vertex.y,(accent?1.92:intersection?1.5:1.04)+depth*.5,0,Math.PI*2);ctx.fill()})
  ctx.restore()
}
